Jax utils py tree refactor
JaxGaussianProcesses/JaxLinOp pull request #20
Opened 2023-03-14 16:23 UTC by Daniel-Dodd

This moves the base class inheritance to `simple-pytree`.

We move `shape` and `dtype` to attributes of the dataclass, and ensure that dtype can be passed to each LinOps `__init__` to override the dtype of the linear operator.

2023-03-14 17:35 UTC, thomaspinder requested changes
Overall looks good. Before approving, I would ideally like to see two things:

1) More documentation would be helpful. A simple notebook demonstrating the functionality of JaxLinOp and some more informative docstrings would be sufficient for now.
2) Coverage - it looks like a report is being uploaded to codecov, but I don't see the percentage anywhere.

2023-03-14 17:35 UTC, thomaspinder commented on jaxlinop/utils.py
> +
Should this not just go into JaxUtils? It contains nothing unique to JaxLinOp.

2023-03-14 17:35 UTC, thomaspinder commented on jaxlinop/linear_operator.py
> +class LinearOperator(Pytree, Generic[ShapeT, DTypeT]):
What does it mean to inherit `Generic[ShapeT, DTypeT]`? Can we make the docstring clearer to acknowledge this please?

2023-03-14 17:35 UTC, thomaspinder commented on jaxlinop/zero_linear_operator.py
> +    if not isinstance(shape, tuple):
Do we not want it be an `Iterable`? I'd have thought a list was valid here.

2023-03-14 17:35 UTC, thomaspinder commented on jaxlinop/zero_linear_operator.py
> +# TODO: Generalise to non-square matrices.
Can we either act on TODOs or open issues for them please

2023-03-14 17:35 UTC, thomaspinder commented on jaxlinop/linear_operator.py
> +    dtype: DTypeT = static_field()
Comments here would be helpful to acknowledge what `static_field` is doing.

2023-03-14 17:35 UTC, thomaspinder commented on jaxlinop/zero_linear_operator.py
>          # TODO: check shapes.
Same comment as above re. TODOs

2023-03-14 19:02 UTC, Daniel-Dodd commented on jaxlinop/utils.py
> +
Perhaps only if it useful for JaxKern, GPJax, ect. Otherwise, it might be best to keep the dependency structure independent, if it is only 4 lines of code? But happy to open an issue on JaxUtils for it to be added in future if there is a good use case.

2023-03-16 18:04 UTC, Daniel-Dodd commented on jaxlinop/zero_linear_operator.py
> +    if not isinstance(shape, tuple):
Will open issue for this.

2023-03-16 18:04 UTC, Daniel-Dodd commented on jaxlinop/zero_linear_operator.py
> +# TODO: Generalise to non-square matrices.
Will open issue for these.

2023-03-16 18:08 UTC, merged